name: lnav
adopt-info: lnav
summary: Log File Navigator
description: |
  The Log File Navigator, **lnav** for short, is an advanced log file viewer
  for the small-scale.

base: core18
grade: stable
confinement: strict

apps:
  lnav:
    command: lnav
    plugs: 
      - home            # optional, allows to read log files from home directory
      - log-observe     # required, provide access to system logs in /var/log
      - network         # required, lnav uses sendto() with UNIX domain socket 

parts:
  selective-checkout:
    source: https://github.com/Lin-Buo-Ren/selective-checkout.git
    source-tag: v1.0.0
    plugin: dump
    build-packages:
    # Uncomment the VCS your main part is using
    - git
    #- mercurial
    #- subversion
    stage:
      - scriptlets/selective-checkout
    prime:
      - -*
  lnav:
    after:
      - selective-checkout
    plugin: autotools
    source: https://github.com/tstack/lnav.git
    source-tag: v0.9.0
    source-depth: 500
    override-pull: |
      snapcraftctl pull

      "$SNAPCRAFT_STAGE"/scriptlets/selective-checkout
    build-packages: 
      - build-essential
      - libpcre3-dev
      - libsqlite3-dev
      - libncursesw5-dev
      - libreadline-dev
      - zlib1g-dev
      - libbz2-dev
      - libgpm-dev
      - libcurl-dev
    stage-packages: 
      - zlib1g
      - libncursesw5
      - libpcre3
      - libgpm2
      - libcurl3-gnutls
