name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Update apt
      run: sudo apt-get update
#    - name: Install packages
#      run: sudo apt-get install libncursesw5-dev libpcre++-dev libsqlite3-dev libbz2-dev libcurl4-openssl-dev libreadline-dev zlib1g-dev lcov
#    - name: install cpp-coveralls
#      run: pip install --user cpp-coveralls
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --enable-code-coverage --enable-debug
    - name: make
      run: make -j2
    - name: make check
      run: make check
    - name: upload cover
      run: coveralls --gcov-options '\-lp'
    - name: make distcheck
      run: make distcheck -j4 || (test -e lnav-*/_build/sub/test/test-suite.log && cat lnav-*/_build/sub/test/test-suite.log)
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Linux 64-bit
        # A file, directory or wildcard pattern that describes what to upload
        path: src/lnav
